name: Flutter CI

on: push
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

env:
  flutter_channel: "beta" # or: 'stable' or 'dev' or 'beta'
  #flutter_version: '2.2.2'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: $flutter_channel
      - run: flutter config --enable-windows-desktop

      - name: windows build
        run: flutter build windows

      - name: 'Upload Windows artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: 'windows-release'
          path: 'build/windows/runner/Release/*'

      - name: 'Create GitHub release'
        #uses: actions/checkout@v3
        uses: ncipollo/release-action@v1
        with:
          commit: '${{ github.sha }}'
          artifacts: "build/windows/runner/Release/*"


      # - name: upload APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: apk
      #     path: out/build/app/outputs/apk/release/app-release.apk
